export const seedPets = [
  {id:'luna',name:'Luna',species:'Dog',breed:'Border Collie mix',age:2,gender:'Female',size:'Medium',color:'Black & white',description:'Luna is bright, affectionate, and always ready for an adventure. She loves long walks, puzzle toys, and curling up near her people after a busy day.',adoptionStatus:'Available',location:'Oslo, Norway',image:{url:'https://images.unsplash.com/photo-1551717743-49959800b1f6?auto=format&fit=crop&w=1200&q=85',alt:'Black and white dog looking at the camera'}},
  {id:'milo',name:'Milo',species:'Cat',breed:'Domestic shorthair',age:3,gender:'Male',size:'Small',color:'Orange tabby',description:'Milo is a gentle, curious cat who enjoys sunny windowsills and quiet company. He warms up quickly and rewards patience with the loudest purr.',adoptionStatus:'Available',location:'Bergen, Norway',image:{url:'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=1200&q=85',alt:'Orange tabby cat'}},
  {id:'poppy',name:'Poppy',species:'Rabbit',breed:'Mini lop',age:1,gender:'Female',size:'Small',color:'Cream',description:'Poppy is an inquisitive little rabbit who loves cardboard tunnels, fresh herbs, and gentle head scratches.',adoptionStatus:'Available',location:'Trondheim, Norway',image:{url:'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?auto=format&fit=crop&w=1200&q=85',alt:'Cream lop-eared rabbit'}},
  {id:'archie',name:'Archie',species:'Dog',breed:'Labrador retriever',age:5,gender:'Male',size:'Large',color:'Chocolate',description:'Archie is a calm, loyal companion with excellent manners. He adores swimming and gets along well with older children.',adoptionStatus:'Pending',location:'Stavanger, Norway',image:{url:'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=1200&q=85',alt:'Chocolate Labrador outdoors'}},
  {id:'olive',name:'Olive',species:'Cat',breed:'Russian Blue mix',age:4,gender:'Female',size:'Small',color:'Grey',description:'Olive is thoughtful and independent but forms a deep bond with her chosen person. A peaceful home would suit her best.',adoptionStatus:'Available',location:'Tromsø, Norway',image:{url:'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=1200&q=85',alt:'Grey cat resting'}},
  {id:'finn',name:'Finn',species:'Dog',breed:'Jack Russell mix',age:3,gender:'Male',size:'Small',color:'White & tan',description:'Finn packs a big personality into a small frame. He is playful, food-motivated, and keen to learn new tricks.',adoptionStatus:'Available',location:'Drammen, Norway',image:{url:'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1200&q=85',alt:'Small white and tan dog'}},
];

export const owner = {name:'Pawfect Home Rescue',email:'hello@pawfecthome.example',bio:'A volunteer-led rescue matching animals with loving homes.',avatar:{url:'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=200&q=80',alt:'Rescue team avatar'},banner:{url:'',alt:''}};

export const hydratePet = pet => ({...pet,created:pet.created||new Date().toISOString(),updated:pet.updated||new Date().toISOString(),owner:pet.owner||owner});
